apiVersion: v1
kind: Secret
metadata:
  name: arthub-secrets
  namespace: user-app
  annotations:
    avp.kubernetes.io/path: "/kv/data/arthub" #path of secret in vault
type: Opaque
stringData:
  AWS_ACCESS_KEY: <AWS_ACCESS_KEY>
  AWS_BUCKET_NAME: <AWS_BUCKET_NAME>
  AWS_SECRET_KEY: <AWS_SECRET_KEY>
  DATABASE_URL: <DATABASE_URL>
  REDIS_URL: <REDIS_URL>
  S3_BASE_URL: <S3_BASE_URL> #Fomat should be like this with keye
