apiVersion: v1
kind: Secret
metadata:
  name: mssql 
  namespace: database
  annotations:
    avp.kubernetes.io/path: "/kv/data/database" #path of secret in vault
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: <MSSQL_SA_PASSWORD>