apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    path:  vault
    repoURL: 'https://helm.releases.hashicorp.com' 
    targetRevision: '0.27.0'
    helm:
      releaseName: vault
      # valueFiles:
      # - $values/infra-deployments/external-dns/cf-myorg--com/bitnami-6.36.1-helm-values.yaml     
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true