apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    chart: 'promtail'
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.15.5 
    helm:
      releaseName: promtail
      valueFiles:
      - https://github.com/1wolfalone1/arthub-cicd-aws-eks-cluster/raw/main/helm-values/promtail.yamll    
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
